name: "seminal"
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build '.#'
    - run: nix run '.#checks.x86_64-linux.seminal-clippy'
